#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on:
#  release:
#    types: [published]
#  push:
#    tags:
#    - 'v*'
#  branches: 
#    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
    - name: Build Firmware
      env:
        TNAME: K2P_nano-5.0
      run: |
        cd /opt/rt-n56u/trunk
        mkdir -p $GITHUB_WORKSPACE/images
        chmod +x $GITHUB_WORKSPACE/diy.sh
        $GITHUB_WORKSPACE/diy.sh
        echo "::set-env name=TNAME::K2P_nano"
    - name: Build Firmware2
      run: |
        $GITHUB_WORKSPACE/diy.sh
        echo "::set-env name=RELEASE_TAG::"$(TZ=UTC-8 date +"%Y.%m.%d")""
    - name: Upload to release
      uses: 1005789164/action-release@master
      with:
        token: ${{ secrets.P_TOKEN }}
        gzip: false
        files: >
          images/*.trx
        allow_override: true
    - name: Push firmware
      env:
        PUSH_TOKEN: ${{ secrets.P_TOKEN }}
      run: |
        mkdir -p firmware-branch
        cd firmware-branch
        git init
        [ -e ../images/*.trx ] && cp ../images/*.trx ./
        ls -al
        git config --local user.email "FUCK@github.com"
        git config --local user.name "FUCK"
        git add -f ./
        git commit -m "firmware"
        git push --force --quiet https://${PUSH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:firmware
        
